export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "surface": "#f7f9ff",
                "on-surface": "#091d2e",
                "on-secondary": "#ffffff",
                "surface-bright": "#f7f9ff",
                "on-primary-container": "#502600",
                "secondary-container": "#fed65b",
                "outline-variant": "#dcc1b1",
                "surface-container-highest": "#d1e4fb",
                "on-primary": "#ffffff",
                "on-tertiary": "#ffffff",
                "surface-container-low": "#edf4ff",
                "inverse-surface": "#203243",
                "tertiary-fixed-dim": "#bcc9ca",
                "secondary": "#735c00",
                "primary-fixed": "#ffdcc5",
                "on-surface-variant": "#564337",
                "on-secondary-container": "#745c00",
                "inverse-primary": "#ffb783",
                "on-error-container": "#93000a",
                "tertiary": "#546162",
                "on-tertiary-container": "#283435",
                "secondary-fixed-dim": "#e9c349",
                "surface-variant": "#d1e4fb",
                "tertiary-fixed": "#d8e5e6",
                "on-background": "#091d2e",
                "outline": "#897365",
                "tertiary-container": "#8f9c9d",
                "on-secondary-fixed-variant": "#574500",
                "primary": "#944a00",
                "secondary-fixed": "#ffe088",
                "on-tertiary-fixed-variant": "#3d494a",
                "inverse-on-surface": "#e8f2ff",
                "background": "#f7f9ff",
                "surface-container": "#e3efff",
                "on-primary-fixed": "#301400",
                "surface-tint": "#944a00",
                "primary-container": "#e67e22",
                "on-secondary-fixed": "#241a00",
                "error": "#ba1a1a",
                "surface-dim": "#c9dcf3",
                "on-error": "#ffffff",
                "primary-fixed-dim": "#ffb783",
                "surface-container-high": "#d9eaff",
                "on-primary-fixed-variant": "#713700",
                "surface-container-lowest": "#ffffff",
                "on-tertiary-fixed": "#121e1f",
                "error-container": "#ffdad6"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "unit": "8px",
                "container-max-width": "1280px",
                "gutter": "24px",
                "margin-mobile": "16px",
                "margin-desktop": "40px"
            },
            "fontFamily": {
                "caption": ["Inter", "sans-serif"],
                "label-md": ["Inter", "sans-serif"],
                "display-lg": ["Montserrat", "sans-serif"],
                "headline-lg": ["Montserrat", "sans-serif"],
                "headline-lg-mobile": ["Montserrat", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "headline-md": ["Montserrat", "sans-serif"]
            },
            "fontSize": {
                "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
                "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
                "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
                "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0.01em", "fontWeight": "400" }],
                "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0.01em", "fontWeight": "400" }],
                "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }]
            }
        }
    },
    plugins: [],
  }
